2018-12-08 07:59:22|ERROR|Warning_Message.Go|exception 'PDOException' with message 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where to_days(createTime)=to_days(now()))' at line 1' in D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php:258
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php(811): NotORM_Result->query('SELECT * FROM v...', Array)
#1 D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php(857): NotORM_Result->execute()
#2 D:\wamp\www\jxc\api\Version1\Model\Message.php(19): NotORM_Result->fetch()
#3 D:\wamp\www\jxc\api\Version1\Domain\Message\Msg.php(87): Model_Message->invoiceMsgExists('41')
#4 D:\wamp\www\jxc\api\Version1\Api\Warning\Message.php(10): Domain_Message_Msg::InvoiceWaning('32')
#5 [internal function]: Api_Warning_Message->go()
#6 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#7 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#8 {main}
2018-12-08 10:15:53|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(71, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 10:16:15|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(70, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 10:16:32|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(69, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 10:24:11|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(72, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 10:44:24|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(73, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 10:59:16|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(74, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 11:05:55|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(75, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 13:07:39|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(76, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 13:33:36|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(77, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 13:43:38|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(78, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 13:52:28|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(79, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 14:01:45|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(80, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 14:55:26|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(81, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 15:06:56|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(82, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-08 15:31:22|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(83, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
